### ISSUE TITLE
incompatible with elasticsearch 6.1

### ISSUE THREAD

**Issue by hkhoshraftar** [NarimanN2/ParsiAnalyzer#1]
after installing plugin it errors 
incompatible with elasticsearch 6.1

![pig](https://user-images.githubusercontent.com/15705556/35193454-d770dfe2-feb7-11e7-852d-98c0efd8cb8f.PNG)

**Comment by NarimanN2** [comment]
Hi, the latest release is compatible with _elastic 5.6.3_. I will make a release compatible with _elastic 6.1_ as soon as possible. but in case you are in hurry please follow these steps:
1- Download the latest source code
2- Open `pom.xml` file
3- Under **dependecies** tag, change elasticserach version from _5.6.3_ to _6.1.2_ and save it
4- Open `plugin-descriptor.properties` file
5- Change elasticsearch.version from _5.6.3_ to _6.1.2_
6- Run this maven command: `mvn clean package -DskipTests`
7- In the folder target/releases you’ll now find a zip file called ParsiAnalyzer. install the plugin using this command:
`bin/elasticsearch-plugin install file:///path/to/ParsiAnalyzer.zip`

please let me know if there is a problem.

**Comment by hkhoshraftar** [comment]
tnx i'll check it

**Comment by MHZarei** [comment]
@hkhoshraftar This solution worked in elastic 6.1.2?
