### ISSUE TITLE
Support elastic search 7.11

### ISSUE THREAD

**Issue by amirpiri** [NarimanN2/ParsiAnalyzer#10]
You don't want support elasticsearch 7.11?

**Comment by NarimanN2** [comment]
Sure. I'll update it to 7.11 as soon as possible, but if you are in a hurry you can build it yourself as explained [here.](https://github.com/NarimanN2/ParsiAnalyzer#build)

**Comment by NarimanN2** [comment]
Hi, ParsiAnalyzer now supports Elasticsearch 7.13.1.
