### ISSUE TITLE
ERROR: Unknown plugin ParsiAnalyzer-1.0-SNAPSHOT.zip

### ISSUE THREAD

**Issue by ashkan-jafarzadeh** [NarimanN2/ParsiAnalyzer#15]
I've followed the [build](https://github.com/NarimanN2/ParsiAnalyzer#build) steps for version 7.17.4 and built the `ParsiAnalyzer-1.0-SNAPSHOT.zip`  under the `target/releases` folder. When I try to install it by `elasticsearch-plugin`, it fails:
```
-> Installing /path/to/ParsiAnalyzer/target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip
-> Failed installing /path/to/ParsiAnalyzer/target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip
-> Rolling back /path/to/ParsiAnalyzer/target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip
-> Rolled back /path/to/ParsiAnalyzer/target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip
A tool for managing installed elasticsearch plugins

Non-option arguments:
command              

Option             Description        
------             -----------        
-E <KeyValuePair>  Configure a setting
-h, --help         Show help          
-s, --silent       Show minimal output
-v, --verbose      Show verbose output

ERROR: Unknown plugin /path/to/ParsiAnalyzer/target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip

```
Any idea about this problem?

**Comment by NarimanN2** [comment]
What is the command that you are using to install the plugin? 
And is `/path/to/ParsiAnalyzer/target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip` the actual path that you are using when installing the plugin? Because it was just an example and you should give the actual absolute path to the zip file on your computer.

**Comment by ashkan-jafarzadeh** [comment]
Thanks for answering.
The command is: `sudo ./elasticsearch-plugin install /path/to/ParsiAnalyzer/target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip`
And of course it is the absolute path, I've just hidden it in my question and replaced it with `/path/to`

**Comment by ashkan-jafarzadeh** [comment]
The problem is solved.
I extracted the zip file and copied it to the `elasticsearch/plugins` folder and then restarted the elasticsearch service. It worked for me.

**Comment by NarimanN2** [comment]
Try this command next time: 

`sudo ./elasticsearch-plugin install file:///path/to/ParsiAnalyzer/target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip`
