### ISSUE TITLE
change & compile

### ISSUE THREAD

**Issue by mohsenMohamadi** [NarimanN2/ParsiAnalyzer#2]
hi,
How to compile after changing the code?

**Comment by NarimanN2** [comment]
Hi
Run this maven command: `mvn clean package`. 
then you can find a zip file in target/releases directory. that is your plugin and you can install it on elasticsearch as follows: 
`bin/elasticsearch-plugin install file:///path/to/target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip`

please let me know if something went wrong.
