### ISSUE TITLE
Error Installing Plugin for Elasticsearch 7.7

### ISSUE THREAD

**Issue by farshaddavoudi** [NarimanN2/ParsiAnalyzer#8]
Hi, I tried to install this Analyzer for Elasticsearch 7.7 but it throws an error as below:
![image](https://user-images.githubusercontent.com/50596689/83736553-0f7e5000-a667-11ea-8d5d-a97ff6d32f0f.png)
It needs to update to 7.7 version, I think. 
Update it please, so we can use it.
Thanks

**Comment by NarimanN2** [comment]
Hi, _ParsiAnalyzer_ is now available for Elasticsearch's latest version, which is 7.8.0.
