### ISSUE TITLE
Error Installing Plugin for Elasticsearch 7.9.2

### ISSUE THREAD

**Issue by MohammadAminPourmoradian** [NarimanN2/ParsiAnalyzer#9]
![image](https://user-images.githubusercontent.com/46063083/95057632-50fd3580-0703-11eb-8407-c5865e2e2777.png)

It needs to update to 7.9
Update it please.thanks

**Comment by NarimanN2** [comment]
Hi, ParsiAnalyzer is now available for Elasticsearch's latest version, which is 7.10.2.
